# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Execute the forward algorithm
#'
#' @param n The length of the timeseries.
#' @param N The number of states in the HMM.
#' @param foo The initial state distributions (delta).
#' @param gamma The transition probability matrix.
#' @param allprobs As outputted by the funtions norm_allporbs
#' @export
foralg <- function(n, N, foo, gamma, allprobs) {
    .Call('_lizardHMM_foralg', PACKAGE = 'lizardHMM', n, N, foo, gamma, allprobs)
}

#' Execute the forward algorithm
#'
#' @param n The length of the timeseries.
#' @param N The number of states in the HMM.
#' @param foo The initial state distributions (delta).
#' @param gamma An array containing the transition probability matrices.
#' @param allprobs As outputted by the funtions norm_allporbs
#' @export
foralg_covar <- function(n, N, foo, gamma, allprobs) {
    .Call('_lizardHMM_foralg_covar', PACKAGE = 'lizardHMM', n, N, foo, gamma, allprobs)
}

